### ISSUE TITLE
Add KCMO logo

### ISSUE THREAD

**Issue by lscott1967** [codeforkansascity/trashday#2]
Please add in upper left-hand corner.

**Comment by pulkonet** [comment]
@lscott1967 Do you need help with this?

**Comment by lscott1967** [comment]
That would be great!

**Comment by zmon** [comment]
@pulkonet most likely you will need to install [Jekyll](https://jekyllrb.com/) or if you would like, I was planning on doing it, convert it to plain HTML) .

Also you can find the KCMO logo at http://codeforkc.org/images/KCMOlogo.png or do a search on "KCMO Logo"

**Comment by pulkonet** [comment]
Can be closed.
